services:
  - type: web
    name: ai-teddy-bear
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.render.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1 --loop uvloop --http httptools
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHON_ENV
        value: production
    healthCheckPath: /health 