# [AI-Generated by Amazon Q]: تم إضافة هذا الكود تلقائياً وفق دليل المشروع.

from fastapi import APIRouter
from fastapi.responses import JSONResponse

router = APIRouter(prefix="/api", tags=["dashboard"])


@router.get("/dashboard/{child_id}/emotions")
async def get_emotions_data(child_id: str, days: int = 7):
    """بيانات المشاعر API"""
    emotion_data = [
        {"date": "2024-01-01", "emotion": "happy", "intensity": 0.8},
        {"date": "2024-01-02", "emotion": "calm", "intensity": 0.6},
        {"date": "2024-01-03", "emotion": "excited", "intensity": 0.9},
    ]
    return JSONResponse(content=emotion_data)


@router.get("/dashboard/{child_id}/progress")
async def get_progress_data(child_id: str):
    """بيانات التقدم API"""
    progress = {
        "status": "active",
        "overall_progress": 85,
        "details": {
            "trivia": {"games_played": 10, "average_score": 85},
            "riddles": {"games_played": 5, "average_score": 78},
        },
    }
    return JSONResponse(content=progress)


@router.get("/dashboard/{child_id}/speech")
async def get_speech_analysis(child_id: str):
    """تحليل النطق API"""
    speech_data = {
        "concerns": [],
        "overall_score": 85,
        "recommendations": ["النطق واضح ومفهوم"],
    }
    return JSONResponse(content=speech_data)


@router.post("/alerts/send")
async def send_parent_alert(alert_data: dict):
    """إرسال تنبيه للوالدين"""
    return JSONResponse(content={"status": "sent", "message": "تم إرسال التنبيه بنجاح"})


@router.get("/dashboard/{child_id}/alerts")
async def get_alerts_history(child_id: str):
    """تاريخ التنبيهات"""
    alerts = [
        {
            "date": "2024-01-01",
            "type": "speech",
            "severity": "low",
            "message": "ملاحظة بسيطة في النطق",
        },
        {
            "date": "2024-01-03",
            "type": "emotion",
            "severity": "medium",
            "message": "تقلبات في المزاج",
        },
    ]
    return JSONResponse(content=alerts)
