global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ai-teddy-bear'

# Alerting rules
rule_files:
  - 'alert_rules.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'

# Scrape configurations
scrape_configs:
  # Scrape metrics from the AI Teddy Bear application
  - job_name: 'ai_teddy_bear'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']
    
    # Optional: Add authentication if needed
    # basic_auth:
    #   username: 'metrics_user'
    #   password: ${PASSWORD}

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']

  # GPU metrics (if using NVIDIA GPUs)
  - job_name: 'gpu_exporter'
    static_configs:
      - targets: ['localhost:9400']

  # Optional: Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  # Optional: Python application metrics
  - job_name: 'python_metrics'
    metrics_path: '/python_metrics'
    static_configs:
      - targets: ['localhost:8000']

# Additional configuration for service discovery
# Uncomment and configure if using dynamic service discovery
# service_discovery:
#   - role: 'pod'
#     kubernetes_sd_configs:
#       - role: pod
#         kubeconfig_file: '/path/to/kubeconfig'
