from typing import Any

"""
EmotionAnalysisResult - Component extracted from large service
مكون منفصل من خدمة كبيرة

Generated by God Class Splitter
"""


class EmotionAnalysisResult:
    """
    EmotionAnalysisResult - Extracted from EmotionAnalysisResult
    Follows Single Responsibility Principle
    """

    def __init__(self, emotion: str, confidence: float):
        """Create a lightweight emotion analysis result.

        Args:
            emotion: Detected primary emotion (e.g., *happy*, *sad*).
            confidence: Model confidence (``0.0``–``1.0``).
        """

        self.emotion = emotion
        # Clamp confidence to [0.0, 1.0]
        self.confidence = max(0.0, min(1.0, float(confidence)))

    def to_dict(self) -> dict[str, Any]:
        """Return a serialisable representation of the analysis result."""

        return {"emotion": self.emotion, "confidence": self.confidence}
