# Transformers imports patched for development
"""
ModerationCore - Component extracted from large service
مكون منفصل من خدمة كبيرة

Generated by God Class Splitter
"""



try:
    from transformers import pipeline
except ImportError:
    pass


