from src.domain.story_generator import PersonalizedStoryGenerator
from src.audio.multi_voice_tts import MultiVoiceTTS
from typing import Dict
import logging

logger = logging.getLogger(__name__)


# [AI-Generated by Amazon Q]: تم إضافة هذا الكود تلقائياً وفق دليل المشروع.


class StoryService:
    """خدمة القصص المتكاملة"""

    def __init__(self, config):
        self.story_generator = PersonalizedStoryGenerator(
            openai_key=config["OPENAI_API_KEY"]
        )
        self.voice_engine = MultiVoiceTTS(
            elevenlabs_key=config["ELEVENLABS_API_KEY"])

    async def create_and_narrate_story(
        self, child_id: str, current_emotion: str, story_type: str = "auto"
    ) -> Dict:
        """إنشاء وسرد قصة مخصصة"""

        # جلب ملف الطفل (افتراضي)
        profile = {"name": "أحمد", "age": 7,
                   "interests": ["الحيوانات", "المغامرات"]}

        # تحديد نوع القصة
        if story_type == "auto":
            theme = self.story_generator.get_story_by_mood(current_emotion)
        else:
            theme = story_type

        # توليد القصة
        story_data = self.story_generator.generate_personalized_story(
            child_name=profile["name"],
            age=profile["age"],
            mood=current_emotion,
            interests=profile["interests"],
            theme=theme,
        )

        # تحويل لصوت متعدد الشخصيات
        audio_file = await self.voice_engine.generate_multi_character_audio(
            story_data["characters"], child_name=profile["name"]
        )

        # حفظ في سجل القصص
        self._save_story_record(child_id, story_data, audio_file)

        return {
            "story_id": story_data["id"],
            "audio_file": audio_file,
            "text": story_data["story"],
        }

    def _save_story_record(self, child_id: str, story_data: Dict, audio_file: str) -> None:
        """حفظ سجل القصة في قاعدة بيانات أو سجل خارجي"""
        # مثال: حفظ في قاعدة بيانات (يجب ربط db فعليًا في التطبيق)
        # db.save_story(child_id, story_data, audio_file)
        logger.info(f"Saving story for child {child_id}: {story_data['id']}")
