# [AI-Generated by Amazon Q]: تم إضافة هذا الكود تلقائياً وفق دليل المشروع.
import os
from dotenv import load_dotenv

# تحميل متغيرات البيئة
load_dotenv()

class Config:
    """إعدادات المشروع"""
    
    # مفاتيح API
    OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
    ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')
    HUME_API_KEY = os.getenv('HUME_API_KEY')
    ELEVENLABS_API_KEY = os.getenv('ELEVENLABS_API_KEY')
    DEEPGRAM_API_KEY = os.getenv('DEEPGRAM_API_KEY')
    
    # قاعدة البيانات
    DATABASE_URL = os.getenv('DATABASE_URL', 'sqlite:///data/teddy_bear.db')
    
    # إعدادات الصوت
    AUDIO_SAMPLE_RATE = 16000
    AUDIO_CHANNELS = 1
    AUDIO_FORMAT = 'wav'
    
    # إعدادات الأمان
    MAX_AUDIO_LENGTH = 60  # ثانية
    MAX_SESSION_DURATION = 3600  # ثانية
    
    # إعدادات التنبيهات
    ALERT_EMAIL_FROM = os.getenv('ALERT_EMAIL_FROM')
    SMTP_SERVER = os.getenv('SMTP_SERVER')
    SMTP_PORT = int(os.getenv('SMTP_PORT', 587))
    
    # إعدادات اللعبة
    GAME_DIFFICULTY_BY_AGE = {
        (3, 5): 'very_easy',
        (6, 8): 'easy',
        (9, 11): 'medium',
        (12, 15): 'hard'
    }
    
    # إعدادات المشاعر
    EMOTION_ALERT_THRESHOLD = 0.7
    EMOTION_HISTORY_DAYS = 30
    
    # إعدادات النطق
    SPEECH_ANALYSIS_ENABLED = True
    SPEECH_CONCERN_THRESHOLD = 3  # عدد المرات قبل التنبيه