version: '3.8'

services:
  audio-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
      - outputs:/app/outputs
      - logs:/logs
    environment:
      - FLASK_ENV=production
      - AUDIO_LOG_LEVEL=INFO

volumes:
  uploads:
  outputs:
  logs:
