# [AI-Generated by Amazon Q]: تم إضافة هذا الكود تلقائياً وفق دليل المشروع.
"""
WSGI config for AI Teddy Bear project.
"""

from main import app
import os
import sys
from pathlib import Path

# إضافة مسار المشروع
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

# تحديد متغيرات البيئة
os.environ.setdefault("DEPLOYMENT_ENV", "production")

# استيراد التطبيق

# تطبيق WSGI
application = app

if __name__ == "__main__":
    import uvicorn

    # SECURITY: Bind to localhost only
    uvicorn.run(application, host="127.0.0.1", port=8000)
