# [AI-Generated by Amazon Q]: تم إضافة هذا الكود تلقائياً وفق دليل المشروع.
"""
WSGI config for AI Teddy Bear project.
"""

import os
import sys
from pathlib import Path

# إضافة مسار المشروع
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

# تحديد متغيرات البيئة
os.environ.setdefault("DEPLOYMENT_ENV", "production")

# استيراد التطبيق
from main import app

# تطبيق WSGI
application = app

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(application, host="0.0.0.0", port=8000)
