# [AI-Generated by Amazon Q]: تم إضافة هذا الكود تلقائياً وفق دليل المشروع.
"""
مزود محتوى الألعاب - يوفر أسئلة وألغاز ومحتوى تعليمي للألعاب التفاعلية
يدعم مستويات صعوبة مختلفة حسب عمر الطفل
"""

from typing import List, Dict
import random

class GameContentProvider:
    """مزود محتوى الألعاب"""
    
    @staticmethod
    def get_trivia_questions(age: int, difficulty: str) -> List[Dict]:
        """أسئلة المعلومات العامة حسب العمر"""
        questions = {
            "very_easy": [
                {"q": "ما لون السماء؟", "a": "أزرق"},
                {"q": "كم عدد أصابع اليد الواحدة؟", "a": "خمسة"},
                {"q": "ما صوت القطة؟", "a": "مواء"},
            ],
            "easy": [
                {"q": "ما هي عاصمة العراق؟", "a": "بغداد"},
                {"q": "كم عدد أيام الأسبوع؟", "a": "سبعة"},
                {"q": "ما أكبر حيوان في العالم؟", "a": "الحوت الأزرق"},
            ],
            "medium": [
                {"q": "كم عدد الكواكب في المجموعة الشمسية؟", "a": "ثمانية"},
                {"q": "ما أطول نهر في العالم؟", "a": "النيل"},
                {"q": "من اخترع المصباح الكهربائي؟", "a": "توماس أديسون"},
            ]
        }
        return questions.get(difficulty, questions["easy"])
    
    @staticmethod
    def get_riddles(difficulty: str) -> List[Dict]:
        """الألغاز حسب الصعوبة"""
        riddles = {
            "easy": [
                {
                    "riddle": "أنا أطير بلا أجنحة، وأبكي بلا عيون. ما أنا؟",
                    "answer": "السحابة",
                    "hints": ["أنا في السماء", "أمطر على الأرض"]
                },
                {
                    "riddle": "لي عين واحدة ولا أستطيع الرؤية. ما أنا؟",
                    "answer": "الإبرة",
                    "hints": ["أستخدم في الخياطة", "لي ثقب صغير"]
                }
            ]
        }
        return riddles.get(difficulty, riddles["easy"])
    
    @staticmethod
    def get_math_problems(age: int) -> List[Dict]:
        """مسائل رياضية حسب العمر"""
        if age < 6:
            return [
                {"problem": "كم يساوي 1 + 1؟", "answer": "2"},
                {"problem": "كم يساوي 2 + 2؟", "answer": "4"}
            ]
        elif age < 10:
            return [
                {"problem": "كم يساوي 5 × 3؟", "answer": "15"},
                {"problem": "كم يساوي 10 ÷ 2؟", "answer": "5"}
            ]
        else:
            return [
                {"problem": "كم يساوي 12 × 8؟", "answer": "96"},
                {"problem": "ما هو جذر 64؟", "answer": "8"}
            ]